# Generated by Django 4.1.3 on 2022-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='orphanageQuantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
