# Generated by Django 4.1.3 on 2022-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddonation', '0002_donate_orphanagequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='orphavailable_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
